Repository nprapps/elections24-general, pull requests merged in 2024-10, with the labels that each got.

#155 state pages with results tables, closes #45
  project.json
  src/_state.html
  src/california.html
  src/css/state.less
  src/css/values.less
  src/js/components/key-races/index.js
  src/js/components/results-collection/index.js
  src/js/components/results-table/_results-table.html
  src/js/components/results-table/index.js
  src/js/components/results-table/results-table.less
  src/js/main.js
  src/js/state.js
  src/partials/_statePageHeader.html
Labels: PR: In review

#158 delete duplicate copy task. closes #157
  tasks/copyAssets.js
Labels: PR: Ready for review

#156 show special election footnote, closes #142
  src/js/components/results-table/_results-table.html
  src/js/components/results-table/index.js
  src/js/state.js
Labels: PR: In review

#165 added name override
  tasks/lib/normalizeResults.js
Labels: PR: Ready for review

#191 added JSDoc and comments where needed
  tasks/elex.js
  tasks/lib/apReports.js
  tasks/lib/apResults.js
  tasks/lib/augmentResults.js
  tasks/lib/nullifyResults.js
Labels: documentation, PR: Draft

#193 added prior_states and the logic
  data/prior_states.csv
  extras/get_prior_states.py
  tasks/lib/augmentResults.js
Labels: PR: Ready for review

#232 fixed the census issue
  data/census_township_data.csv
  get_township_data.py
  tasks/lib/augmentResults.js
Labels: PR: Ready for review

#234 unemployment fix
  data/township_unemployment.csv
  data/unemployment_data.csv
  data/unemployment_township.csv
  get_unemployment_data.py
  tasks/lib/augmentResults.js
Labels: PR: Ready for review

#229 add a script for ap poll hours
  extras/get_ap_poll_hours.js
Labels: PR: Ready for review
